[main 0c42d5e] Add update
 6 files changed, 10 insertions(+), 3 deletions(-)
 create mode 100644 benzin.log
To https://github.com/GermanPaul12/Benzinpreise-Analysis-Heidelberg.git
   a8bf908..0c42d5e  main -> main
File successfully pushed to the remote repository.
Traceback (most recent call last):
  File "/home/german/Documents/Coding/Benzinpreise-Analysis-Heidelberg/benzin.py", line 53, in <module>
    prices[0], prices[1], prices[2]
IndexError: list index out of range
[main a47fb15] Add update
 5 files changed, 346 insertions(+)
To https://github.com/GermanPaul12/Benzinpreise-Analysis-Heidelberg.git
   0c42d5e..a47fb15  main -> main
File successfully pushed to the remote repository.
[main d037c1d] Add update
 5 files changed, 341 insertions(+)
To https://github.com/GermanPaul12/Benzinpreise-Analysis-Heidelberg.git
   a47fb15..d037c1d  main -> main
File successfully pushed to the remote repository.
[main 5f12665] Add update
 5 files changed, 341 insertions(+)
To https://github.com/GermanPaul12/Benzinpreise-Analysis-Heidelberg.git
   d037c1d..5f12665  main -> main
File successfully pushed to the remote repository.
[main e45db17] Add update
 5 files changed, 509 insertions(+)
To https://github.com/GermanPaul12/Benzinpreise-Analysis-Heidelberg.git
   5f12665..e45db17  main -> main
File successfully pushed to the remote repository.
[main da208d0] Add update
 5 files changed, 341 insertions(+)
To https://github.com/GermanPaul12/Benzinpreise-Analysis-Heidelberg.git
   e45db17..da208d0  main -> main
File successfully pushed to the remote repository.
[main 1e6080e] Add update
 5 files changed, 341 insertions(+)
To https://github.com/GermanPaul12/Benzinpreise-Analysis-Heidelberg.git
   da208d0..1e6080e  main -> main
File successfully pushed to the remote repository.
Traceback (most recent call last):
  File "/home/german/Documents/Coding/Benzinpreise-Analysis-Heidelberg/benzin.py", line 53, in <module>
    prices[0], prices[1], prices[2]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/german/Documents/Coding/Benzinpreise-Analysis-Heidelberg/benzin.py", line 53, in <module>
    prices[0], prices[1], prices[2]
IndexError: list index out of range
[main d6440c7] Add update
 5 files changed, 503 insertions(+)
To https://github.com/GermanPaul12/Benzinpreise-Analysis-Heidelberg.git
   1e6080e..d6440c7  main -> main
File successfully pushed to the remote repository.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f98184160>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.benzinpreis.de', port=443): Max retries exceeded with url: /aktuell/super_e5/deutschland/baden-wuerttemberg/karlsruhe/landkreis_heidelberg/heidelberg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f98184160>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/german/Documents/Coding/Benzinpreise-Analysis-Heidelberg/benzin.py", line 31, in <module>
    response = requests.get(
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.benzinpreis.de', port=443): Max retries exceeded with url: /aktuell/super_e5/deutschland/baden-wuerttemberg/karlsruhe/landkreis_heidelberg/heidelberg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f98184160>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[main f2837d2] Add update
 5 files changed, 385 insertions(+)
To https://github.com/GermanPaul12/Benzinpreise-Analysis-Heidelberg.git
   d6440c7..f2837d2  main -> main
File successfully pushed to the remote repository.
[main 40640df] Add update
 5 files changed, 341 insertions(+)
To https://github.com/GermanPaul12/Benzinpreise-Analysis-Heidelberg.git
   f2837d2..40640df  main -> main
File successfully pushed to the remote repository.
Traceback (most recent call last):
  File "/home/german/Documents/Coding/Benzinpreise-Analysis-Heidelberg/benzin.py", line 53, in <module>
    prices[0], prices[1], prices[2]
IndexError: list index out of range
[main c535b16] Add update
 5 files changed, 506 insertions(+)
To https://github.com/GermanPaul12/Benzinpreise-Analysis-Heidelberg.git
   40640df..c535b16  main -> main
File successfully pushed to the remote repository.
[main 793566a] Add update
 5 files changed, 341 insertions(+)
To https://github.com/GermanPaul12/Benzinpreise-Analysis-Heidelberg.git
   c535b16..793566a  main -> main
File successfully pushed to the remote repository.
[main fa02aca] Add update
 5 files changed, 341 insertions(+)
To https://github.com/GermanPaul12/Benzinpreise-Analysis-Heidelberg.git
   793566a..fa02aca  main -> main
File successfully pushed to the remote repository.
Traceback (most recent call last):
  File "/home/german/Documents/Coding/Benzinpreise-Analysis-Heidelberg/benzin.py", line 53, in <module>
    prices[0], prices[1], prices[2]
IndexError: list index out of range
[main ab9a8d6] Add update
 5 files changed, 506 insertions(+)
To https://github.com/GermanPaul12/Benzinpreise-Analysis-Heidelberg.git
   fa02aca..ab9a8d6  main -> main
File successfully pushed to the remote repository.
[main 5e85dfa] Add update
 5 files changed, 341 insertions(+)
To https://github.com/GermanPaul12/Benzinpreise-Analysis-Heidelberg.git
   ab9a8d6..5e85dfa  main -> main
File successfully pushed to the remote repository.
[main 08f9853] Add update
 5 files changed, 341 insertions(+)
To https://github.com/GermanPaul12/Benzinpreise-Analysis-Heidelberg.git
   5e85dfa..08f9853  main -> main
File successfully pushed to the remote repository.
